### PR TITLE
check in .proto files to unbreak go-control-plane

### PR DESCRIPTION
**Pull request by thomasco**
Removing .proto files in 929161cd91197d0ba0eab67b083a886db13295cd broke go-control-plane. I removed `.gitignore` (which only contained .proto) and ran `make`.

### CODE REVIEW

**Comment by kyessenov** [comment]
Please CLA to get this merged.
FYI, I'm trying to clean up Envoy's go build systematically here https://github.com/envoyproxy/envoy/issues/7982. Starting with goproto, and then moving on to gogoproto.

**Comment by thomasco** [comment]
Ping again, still blocked on getting this PR merged. cc @sdake or @geeknoid in case one of you can approve instead.

**Comment by geeknoid** [comment]
Sorry, I hadn't seen this.

Can you explain why you need protos from this repo for a downstream repo? This repo is supposed to just contained generated go code, not the original protos.

@sdake is working on a PR that makes it easy for any repos to import protos that they need. This will be rolled out to istio/api, istio/gogo-genproto, istio/operator. Perhaps this is a better choice for go-control-plane.

**Comment by geeknoid** [comment]
And what is go-control-plane?

**Comment by sdake** [comment]
Please hold for PR: https://github.com/istio/gogo-genproto/pull/21

**Comment by sdake** [comment]
Does go-control-plane use these protos?  If so, we should add that to our plan.  What is the cononical source for go-control-plane's upstream repo?

Cheers
-steve

**Comment by sdake** [comment]
@geeknoid - see https://github.com/istio/gogo-genproto/pull/21#issue-312467329.  TLDR - the `pb.go` generated files will land in different locations.

The current function of this repository is to basically do what `get_protos.sh` from common-files does (pin to specific versions of the protos) but then also to generate `pb.go` files (and probably some other work.  I probably won't have a merge of my work until Tuesday (open house, 3 birthdays, labor day, tonearm mounting) at the earliest - sorting out just this repository is a big job.  I am assuming (possibly incorrectly) that the `pb.go` paths must not change.

**Comment by geeknoid** [comment]
@sdake Correct, the .pb.go paths must not change.

**Comment by geeknoid** [comment]
https://github.com/istio/gogo-genproto/pull/22 is reintroducing protos, but in a different location than before. They're coming down as part of our common files (from the istio/common-files repo). So I'm closing this PR.

I also urge you to not take a dependency on these proto files in this repo. If you need the protos, get them from their real home location on the interwebs.

**Pull request closed without merging**
