### PR TITLE
Add protos

### PR DESCRIPTION
**Pull request by kyessenov**
Useful when building gogo protos that depend on googleapis.

### CODE REVIEW

**Comment by kyessenov** [comment]
probably need some protection here since apparently I don't you guys to approve this :)

**Comment by douglas-reid** [comment]
I'm very confused as to what happened here. Did you just merge because you saw that you could and then realize there had been no approvals?

In general, this seems fine to me. I think there were previous objections to copying the protos over into another repo. But I don't feel that strongly about it, as these particular protos will likely never change.

I wonder if we need stronger warnings in the README, etc., that indicate that these are only copies and should not be considered the source-of-truth for the googleapis protos, or something along those lines.

I guess the next step is to update the builds in istio/api and istio/istio to use these from their vendor/ dirs instead of downloading from the googleapis repo. Are you going to handle that too?

**Comment by kyessenov** [comment]
Yeah, I was assuming this is a go dependency, so no harm can be made by checking in non-go files.

Agree about proper warnings. I think it's useful to preserve the modifications to protos to avoid repeating the replace operation in every consumer of this repo. @wora also suggested to add `google.type` and `google.api.http`, which can be done in a follow-up. We may get an official googleapis gogo proto repo down the line.

I'll try to hook it up against https://github.com/envoyproxy/go-control-plane first, to see how gogoslick and gogo interact. If that works, I can take a stab at istio/api.

**Comment by kyessenov** [comment]
Sorry if I was too quick, it's easy to revert this if there are objections :)

**Pull request merged**
